version: '3.5'

services:
  build:
    container_name: proxy_netcore_build
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - ../../volumes/hqm-server-proxy/hqm-server-proxy:/app
    working_dir: /app
    command: /bin/bash -c "dotnet restore && dotnet publish -c Release"
  netcore:
    container_name: proxy_netcore
    restart: unless-stopped
    build: ./app
    depends_on:
      - build
    environment:
      - DLL_NAME=hqm-server-proxy.dll
    ports:
      - "27585:27585/udp"
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    volumes:
      - ../../volumes/hqm-server-proxy/hqm-server-proxy/bin/Release/net8.0/publish:/app/publish